In [1]:
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

import h5py
import pandas as pd
import numpy as np
import copy
import os
import sys
import matplotlib.pyplot as plt
from sklearn.externals import joblib

In [2]:
# load data file names
working_folder = ".."
data_folder = os.path.join(working_folder, 'data')
format1_files = ['data_format1_201808.h5']
format2_files = ['data_format2_201808.h5']
# load data
cur_datas = pd.DataFrame()
cur_datas_f2 = pd.DataFrame()
opened_files = list()
i=0
# for f in format1_files:
f = format1_files[0]
f_fp = os.path.join(data_folder, f)
f1_data = pd.HDFStore(f_fp)
if i==0:
    print(f1_data.keys())
i += 1
opened_files.append(f1_data)
cur_bch = f1_data['BCH-USD']

if not cur_datas.empty:
    cur_datas = cur_datas.append(cur_bch)
else:
    cur_datas = cur_bch

['/BCH-USD', '/BTC-USD', '/ETH-USD', '/LTC-USD']


In [3]:
for f in opened_files:
    f.close()

In [4]:
f = format2_files[0]
f_fp = os.path.join(data_folder, f)
# f2_data = pd.HDFStore(f_fp)
f2_data = h5py.File(f_fp, mode='r')
opened_files.append(f2_data)
times = list(f2_data.keys())

In [5]:
data_cur_min = f2_data[times[0]][:]
data_cur_min[:,0:4]

array([[ 776.96,  776.96,  776.28,  776.28],
       [7730.77, 7731.91, 7727.27, 7727.28],
       [ 432.95,  432.95,  432.36,  432.36],
       [  79.02,   79.07,   78.88,   78.88]])

In [6]:
np.mean(data_cur_min[:,0:4], axis=1)

array([ 776.62  , 7729.3075,  432.655 ,   78.9625])

In [7]:
data_cur_min[1,]

array([7.73077000e+03, 7.73191000e+03, 7.72727000e+03, 7.72728000e+03,
       3.50382689e+00])

In [8]:
from datetime import datetime as dt
from datetime import timedelta

In [9]:
?timedelta